/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dp.linear.longest_increasing_subsequence;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {

    /** https://en.wikipedia.org/wiki/Longest_increasing_subsequence */
    @Test 
    void wikipediaSolution() {
        Solution sol = new Solution();
        int[] vals = new int[] { 0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15};

        assertEquals(sol.compute(vals), 6);
    }

    /** https://www.geeksforgeeks.org/dsa/longest-increasing-subsequence-dp-3/ */
    @Test 
    void geeksForGeeksSolution() {
        Solution sol = new Solution();
        int[] vals = new int[] { 3, 10, 2, 1, 20};

        assertEquals(sol.compute(vals), 3);
    }

}